const tpl_app = require('./tpl_app'),
  tpl_index = require('./tpl_index'),
  tpl_log = require('./tpl_log'),
  tpl_router_ext = require('./tpl_router_ext'),
  tpl_config = require('./tpl_config'),
  tpl_db_development = require('./tpl_db_development'),
  tpl_db_staging = require('./tpl_db_staging'),
  tpl_db_production = require('./tpl_db_production'),
  tpl_mysql = require('./tpl_mysql'),
  tpl_redis = require('./tpl_redis'),
  tpl_mongo = require('./tpl_mongo'),
  tpl_qiniu = require('./tpl_qiniu'),
  tpl_router = require('./tpl_router'),
  tpl_tools = require('./tpl_tools'),
  tpl_dao = require('./tpl_dao');
  tpl_dao_mysql = require('./tpl_dao_mysql');

module.exports = {
  app: tpl_app,
  index: tpl_index,
  log: tpl_log,
  koa_router_ext: tpl_router_ext,
  config: tpl_config,
  db_development: tpl_db_development,
  db_staging: tpl_db_staging,
  db_production: tpl_db_production,
  mysql: tpl_mysql,
  redis: tpl_redis,
  mongo: tpl_mongo,
  qiniu: tpl_qiniu,
  base_router: tpl_router,
  base_dao: tpl_dao,
  tools: tpl_tools,
  mysql_dao: tpl_dao_mysql
}